### ISSUE TITLE
In iOS mail trigger the interpret message function by clicking on forward - wrong message

### ISSUE THREAD

**Issue by Nock-zz** [DimensionDev/Tessercube-iOS#56]
On an iPhone 6S

1. In iOS mail if I copy the "Received PGP message" and go to the Tessercube app and click on Interpret - the message can be interpreted - no problem.

2. As a second option I tried Reply (or Forward) to bring up the Tesseract keyboard and was surprised to find a summary of the interpreted message. HOWEVER, the summary interpretation was **not always for the message I was reading**  - it was sometimes for a previous message.
This was confusing.

**### Question**
I am doing something wrong or is this just a message to let you know an interpretation is available under Tessercube - Interpret (for a previous message).

Thanks,

Nick

**Comment by neruthes** [comment]
I believe that the confusion you mentioned was mainly due to the lack of a system-wide clipboard-content-change event, and thus we have to implement something similar in order to allow copy-to-interpret. If there is such an event for listening or there is an API to insert an option in the contextual menu for text selection, we should be able to let a user interpret encrypted messages in an IM conversation without leaving the app.

However, our implementation of simulation of clipboard-content-change event might have problems. I guess, the mechanism of our simulation is that the keyboard tries comparing current clipboard content with the last one it remembered. Therefore, during each comparison, if the current clipboard content looks like to contain a substring which is a valid OpenPGP message payload, the keyboard will offer the interpretation of the message when it gets opened.

Probably you may have some tests to see if all your cases are covered in this scenario. If there is any problem beyond the scope of this, my engineering colleagues will be interested in looking into details.

Also, if you have any idea on improving the copy-to-interpret feature, let me know.

And thank you for writing our first non-internal issue here. `([I:b])`

**Comment by Nock-zz** [comment]
I will wait to install the testflight version you have - can you send me the links and instructions. Maybe my direct app store download is an old version - where can I check the version?

Forgot to say I love the concept of Tessercube.

Nick

**Comment by jk234ert** [comment]
Hi Nick,

Due to the restriction of iOS, the Tessercube keyboard may unexpectedly treat content in the pasteboard as a "new" OpenPGP message, and displays the message you have read constantly.

We are still looking for the optimization method, let me mark this as "enhancement", we'll notify you once we fix this in a later version.

**Comment by Tedko** [comment]
@Nock-zz hi nick, I just add you into testflight group using your email on github. You should receive a notification shortly. We will release the latest testflight for external tester soon as well
